package com.far.suller.models

enum class Skills(val title: String) {

    Android(title = "Android Development"),
    AndroidSDK(title = "Android SDK"),
    Kotlin(title = "Kotlin"),
    Java(title = "Java"),
    JC(title = "Jetpack Compose"),
    XML(title = "XML"),
    Coroutine(title = "Kotlin Coroutine"),
    UIImplementation(title = "UI Implementation"),
    MVVM(title = "MVVM"),
    CLEAN(title = "CLEAN"),
    VersionControl(title = "Version Control"),
    Git(title = "Git"),
    RESTAPI(title = "Rest API"),
    CICD(title = "CI/CD"),
    UnitTesting(title = "Unit Testing"),
    Hilt(title = "Hilt"),
    Koin(title = "Koin"),
    Room(title = "Room"),
    Modularization(title = "Modular"),
    JIRA(title = "JIRA"),
    Gitlab(title = "Gitlab"),
    Bitbucket(title = "Bitbucket"),
    Figma(title = "Figma"),
    ThirdParty(title = "Third Party Api"),
    RxKotlin(title = "RxKotlin"),
    AdIntegration(title = "Ads Integration"),
    Firebase(title = "Firebase"),
    OOP(title = "OOP"),
    Leadership(title = "Leadership"),
    Linux(title = "Linux"),
    SQL(title = "SQL"),
    Flutter(title = "Flutter"),
    Dart(title = "Dart"),
    Unity(title = "Unity"),
    CSharp(title = "C#"),
}